

export const FETCH_RANDOM_USER = 'FETCH_RANDOM_USER'
export const FETCH_RANDOM_USER_SUCCESS = 'FETCH_RANDOM_USER_SUCCESS'
export const FETCH_RANDOM_USER_FAILURE = 'FETCH_RANDOM_USER_FAILURE'
export const PAGINATION_DATA="PAGINATION_DATA"
export const RANDOM_ROW_FILTER="RANDOM_ROW_FILTER"